---
title: "607 Lab 10 sentiment analysis"
author: "Chi Hang(Philip) Cheung"
date: "2024-11-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r pressure, echo=FALSE}
library(tidytext)
library(tidyverse)
```

e:

```{r}
get_sentiments("bing") %>% 
  group_by(sentiment) %>% 
  count(sentiment)
url<- "https://raw.githubusercontent.com/stormwhale/data-mines/refs/heads/main/sentimentdataset.csv"

tweet<- read.csv(url) %>% 
  select(c(Year, Text))

tok_tweet<- tweet %>% 
  unnest_tokens(word, Text)

data("stop_words")
clean_tweet<- tok_tweet %>% 
  anti_join(stop_words)

clean_tweet %>% 
  count(word, sort = TRUE) %>% 
  slice_max(n, n = 10) %>% 
  mutate(word = reorder(word, n)) %>% 
  ggplot(aes(n, word)) +
  geom_col() +
  labs(title = "Top ten frequently used tweeter words")
```
```{r}
aff_score<- clean_tweet %>% 
  inner_join(get_sentiments('afinn'), by = "word") %>% 
  group_by(Year) %>% 
  summarise(sentiment=sum(value))



ggplot(aff_score, aes(x=Year, y=sentiment))+
  geom_bar(stat='identity')+
  scale_x_continuous(breaks = seq(2010, 2023, 1))+
  labs(title = 'Overall tweeter sentiment by years')
```

